version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.26.0
    ports:
      - "9090:9090"

  dynamo-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    networks:
      - dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath .'

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
      
  

  