version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.26.0
    ports:
      - "9090:9090"

  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
      
  

  